name: CI
on:
  push:
    branches:
      - master
      - jerk
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: windows-latest

    steps:

    - name: Set up .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: jenk

    - name: Install Dependencies
      run: dotnet restore

    - name: Make an app build
      run: dotnet build --configuration Release

    - name: Test app
      run: dotnet test
